; AuraBip — PlatformIO
[platformio]
default_envs = silent

[env]
framework = arduino
platform = espressif32
board = heltec_wifi_lora_32_V3   ; V4 nutzt V3-Definition (pin-kompatibel lt. Heltec)
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
    olikraus/U8g2@^2.35.19

[env:silent]

[env:audio]
build_flags = -D VARIANT_AUDIO
